Repository WildCodeSchool/orleans-0219-php-grand-hotel, pull requests merged in 2019-04, with the labels that each got.

#1 ajout des fichiers modifiés
  composer.lock
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
  src/View/layoutVisitor.html.twig
Labels: Changes requested, Corrections done

#2 ajout de la partie footer
  public/assets/css/style.css
  public/assets/images/contact-hotel.png
  public/assets/images/logo_hotel.png
  public/assets/images/office.png
  public/assets/images/qualite.jpg
  public/assets/images/trip.png
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#3 Dev
  composer.lock
  public/assets/css/style.css
  public/assets/images/contact-hotel.png
  public/assets/images/logo_hotel.png
  public/assets/images/office.png
  public/assets/images/qualite.jpg
  public/assets/images/trip.png
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
  src/View/Item/_footer.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
  src/View/layoutVisitor.html.twig
Labels: Reviewed by PO

#4 suppression des commentaires superflus
  public/assets/css/style.css
  public/assets/images/trip.png
  src/View/Item/_footer.html.twig
Labels: Reviewed by PO

#8 Sprint01 us01 navbar
  public/assets/css/style.css
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Corrections done, Reviewed by PO

#9 Sprint02 us07 home carrousel
  public/assets/css/style.css
  public/assets/images/homeCarrousel/hotelfacade.jpg
  public/assets/images/homeCarrousel/jeannedarc.jpg
  public/assets/images/homeCarrousel/room.jpg
  src/View/Home/_HomeCarroussel.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#11 Sprint01 us05 page chambres
  .gitignore
  config/db.php.dist
  public/assets/css/style.css
  public/assets/images/favicon.ico
  public/assets/images/trip.png
  src/Controller/HomeController.php
  src/Controller/RoomController.php
  src/Model/AbstractManager.php
  src/Model/RoomManager.php
  src/View/Item/_footer.html.twig
  src/View/Rooms/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#13 Sprint02 us08 access
  public/assets/css/style.css
  src/View/Home/contactAccueil.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#14 Dev
  public/assets/css/style.css
  public/assets/images/homeCarrousel/hotelfacade.jpg
  public/assets/images/homeCarrousel/jeannedarc.jpg
  public/assets/images/homeCarrousel/room.jpg
  src/View/Home/_HomeCarroussel.html.twig
  src/View/Home/contactAccueil.html.twig
  src/View/Home/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
  src/View/layoutVisitor.html.twig
Labels: Conflicts

#16 Sprint02 fix01
  public/assets/css/style.css
  public/assets/images/homeCarrousel/hotelfacade.jpg
  public/assets/images/homeCarrousel/jeannedarc.jpg
  public/assets/images/homeCarrousel/room.JPG
  public/assets/images/homeCarrousel/room.jpg
  public/assets/images/trip.png
  public/assets/images/tripadvisor.png
  src/Controller/HomeController.php
  src/View/Contact/index.html.twig
  src/View/Home/_HomeCarroussel.html.twig
  src/View/Home/contactAccueil.html.twig
  src/View/Home/index.html.twig
  src/View/Rooms/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#17 liens navbar
  public/assets/css/style.css
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#18 Sprint02 us10 page galery
  .gitignore
  composer.lock
  public/assets/css/style.css
  src/Controller/GaleryController.php
  src/Model/GaleryManager.php
  src/View/Galery/index.html.twig
Labels: Reviewed by PO

#21 Sprint03 us28 accueil services
  .gitignore
  public/assets/css/style.css
  src/View/Home/HomeServices.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#24 Sprint03 fix
  public/assets/css/style.css
  src/View/Galery/index.html.twig
  src/View/Home/HomeServices.html.twig
  src/View/_footer.html.twig
Labels: Corrections done, Reviewed by PO

#25 finalisation de la page seminaire statique version 1
  public/assets/css/style.css
  public/assets/images/seminaire/reunion.jpg
  src/Controller/SeminarController.php
  src/View/Seminar/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed by PO

#29 Dev
  .gitignore
  public/assets/css/style.css
  public/assets/images/halftone.png
  public/assets/images/seminaire/reunion.jpg
  public/assets/images/services/amex.png
  public/assets/images/services/animaux.png
  public/assets/images/services/ascenseur.png
  public/assets/images/services/cartebancaire.png
  public/assets/images/services/chequevacances.png
  public/assets/images/services/fax.png
  public/assets/images/services/nonfumeur.png
  public/assets/images/services/sallereunion.png
  public/assets/images/services/wifi.png
  src/Controller/SeminarController.php
  src/View/Galery/index.html.twig
  src/View/Home/HomeServices.html.twig
  src/View/Home/_HomeCarroussel.html.twig
  src/View/Home/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#27 Sprint03 fix rooms
  src/Controller/RoomController.php
  src/Model/RoomManager.php
  src/View/Room/index.html.twig
Labels: Corrections done, Reviewed by PO

#30 Sprint03 us16 commentaires
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/View/Review/index.html.twig
Labels: Corrections done, Reviewed by PO

#31 Sprint03 fix
  .gitignore
  public/assets/css/style.css
  public/assets/images/galerie/accueilhotel.jpeg
  public/assets/images/galerie/buffetdejeuner.jpeg
  public/assets/images/galerie/chambreconfort.jpeg
  public/assets/images/galerie/chambreconfort.jpg
  public/assets/images/galerie/chambrestandard.jpeg
  public/assets/images/galerie/chambresuperieure.jpg
  public/assets/images/galerie/entreehotel.jpeg
  public/assets/images/galerie/hotelfacade.jpeg
  public/assets/images/galerie/index3.jpeg
  public/assets/images/galerie/salledebain.jpeg
  public/assets/images/galerie/salledereunion.jpg
  public/assets/images/halftone.png
  public/assets/images/ricepaper2.png
  src/View/Galery/index.html.twig
  src/View/Home/HomeServices.html.twig
  src/View/Home/description.html.twig
  src/View/Seminar/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
Labels: Corrections done, Reviewed by PO

#35 Sprint04 us33 admin general chambres
  src/Controller/AdminController.php
  src/Model/AdminRoomManager.php
  src/View/Admin/rooms.html.twig
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed by PO

#38 création page ajout commentaires
  src/Controller/ReviewController.php
  src/Model/ReviewManager.php
  src/Services/CleanForm.php
  src/View/Review/addreview.html.twig
Labels: Corrections done, Reviewed by PO

#33 Sprint03 us4 room index
  src/Controller/HomeController.php
  src/Model/RoomManager.php
  src/View/Home/RoomIndex.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#37 module de gestion de l'apparition des commentaires
  src/Controller/AdminController.php
  src/Model/AdminReviewManager.php
  src/Services/CleanForm.php
  src/View/Admin/review.html.twig
Labels: Corrections done, Reviewed by PO

#41 Dev
  .gitignore
  public/assets/css/style.css
  public/assets/images/galerie/accueilhotel.jpeg
  public/assets/images/galerie/buffetdejeuner.jpeg
  public/assets/images/galerie/chambreconfort.jpeg
  public/assets/images/galerie/chambreconfort.jpg
  public/assets/images/galerie/chambrestandard.jpeg
  public/assets/images/galerie/chambresuperieure.jpg
  public/assets/images/galerie/entreehotel.jpeg
  public/assets/images/galerie/hotelfacade.jpeg
  public/assets/images/galerie/index3.jpeg
  public/assets/images/galerie/salledebain.jpeg
  public/assets/images/galerie/salledereunion.jpg
  public/assets/images/halftone.png
  public/assets/images/ricepaper2.png
  src/Controller/AdminController.php
  src/Controller/HomeController.php
  src/Controller/ReviewController.php
  src/Controller/RoomController.php
  src/Model/AdminReviewManager.php
  src/Model/AdminRoomManager.php
  src/Model/ReviewManager.php
  src/Model/RoomManager.php
  src/Services/CleanForm.php
  src/View/Admin/review.html.twig
  src/View/Admin/rooms.html.twig
  src/View/Galery/index.html.twig
  src/View/Home/HomeServices.html.twig
  src/View/Home/RoomIndex.html.twig
  src/View/Home/description.html.twig
  src/View/Home/index.html.twig
  src/View/Review/addreview.html.twig
  src/View/Review/index.html.twig
  src/View/Room/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#36 formulaire de création de chambres
  src/Controller/AdminController.php
  src/Model/AdminRoomManager.php
  src/Services/AddPictures.php
  src/Services/CleanForm.php
  src/View/Admin/addroom.html.twig
Labels: Corrections done, Reviewed by PO

#40 fix remise de layout admin que j'ai supprimé lors d'un merge
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#34 création page accueil admin
  src/Controller/AdminController.php
  src/View/Admin/index.html.twig
  src/View/layoutAdmin.html.twig
Labels: Conflicts, Corrections done

#39 Sprint03 us21 w epage
  public/assets/css/style.css
  public/assets/images/WE/Ile-Charlemagne.jpg
  public/assets/images/WE/archeologie.jpg
  public/assets/images/WE/biodiversite.jpg
  public/assets/images/WE/cathedrale.jpg
  public/assets/images/WE/geomotifs.jpg
  public/assets/images/WE/glace.jpg
  public/assets/images/WE/jardins.jpg
  public/assets/images/WE/jeanne.jpg
  public/assets/images/WE/parc-floral.jpg
  src/Controller/WeekEndController.php
  src/View/Home/RoomIndex.html.twig
  src/View/WeekEnd/index.html.twig
  src/View/_navbar.html.twig
Labels: Corrections done, Reviewed by PO

#46 ajout condition room controller pour pas de carac, modif insert
  src/Controller/AdminController.php
  src/Model/AdminRoomManager.php
Labels: Reviewed by PO

#47 modif adresse lien navbar
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#42 Sprint02 us06 contact
  composer.json
  composer.lock
  public/assets/css/style.css
  public/assets/images/gares(1).jpg
  public/assets/images/logo_hotel.png
  public/assets/images/train-logo.png
  public/assets/images/tram-logo.png
  public/assets/images/voiture-logo.png
  src/Controller/ContactController.php
  src/Model/ContactManager.php
  src/Services/CleanForm.php
  src/View/Contact/index.html.twig
Labels: Corrections done, Reviewed by PO

#48 ajout d'un else pour prendre en compte les null
  src/Controller/ReviewController.php
Labels: Reviewed by PO

#49 Sprint04 fix02
  public/assets/css/style.css
  src/View/Home/RoomIndex.html.twig
  src/View/Home/contactAccueil.html.twig
  src/View/Room/index.html.twig
Labels: Reviewed by PO

#50 Dev
  composer.json
  composer.lock
  public/assets/css/style.css
  public/assets/images/WE/Ile-Charlemagne.jpg
  public/assets/images/WE/archeologie.jpg
  public/assets/images/WE/biodiversite.jpg
  public/assets/images/WE/cathedrale.jpg
  public/assets/images/WE/geomotifs.jpg
  public/assets/images/WE/glace.jpg
  public/assets/images/WE/jardins.jpg
  public/assets/images/WE/jeanne.jpg
  public/assets/images/WE/parc-floral.jpg
  public/assets/images/gares(1).jpg
  public/assets/images/logo_hotel.png
  public/assets/images/train-logo.png
  public/assets/images/tram-logo.png
  public/assets/images/voiture-logo.png
  src/Controller/AdminController.php
  src/Controller/ContactController.php
  src/Controller/ReviewController.php
  src/Controller/WeekEndController.php
  src/Model/AdminRoomManager.php
  src/Model/ContactManager.php
  src/Services/AddPictures.php
  src/Services/CleanForm.php
  src/View/Admin/addroom.html.twig
  src/View/Admin/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/RoomIndex.html.twig
  src/View/Home/contactAccueil.html.twig
  src/View/Room/index.html.twig
  src/View/WeekEnd/index.html.twig
  src/View/_navbar.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#51 ajout suppression chambre
  src/Controller/AdminController.php
  src/Model/AdminRoomManager.php
  src/Services/AddPictures.php
  src/View/Admin/rooms.html.twig
Labels: Reviewed by PO

#52 la fonction suppression effective ne marchait pas
  src/Controller/AdminController.php
Labels: Reviewed by PO

#54 Sprint04 fix03
  public/assets/css/style.css
  src/Controller/GaleryController.php
  src/Model/GaleryManager.php
  src/View/Contact/index.html.twig
  src/View/Room/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/WeekEnd/index.html.twig
Labels: Reviewed by PO

#55 ajout du lien commentaires dans la navbar visitor
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#61 modification de la fonction GET pour message success et suppression d…
  src/View/Contact/index.html.twig
Labels: Reviewed by PO

#60 Dev
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Controller/GaleryController.php
  src/Model/AdminRoomManager.php
  src/Model/GaleryManager.php
  src/Services/AddPictures.php
  src/View/Admin/rooms.html.twig
  src/View/Contact/index.html.twig
  src/View/Room/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/WeekEnd/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#62 correction boucle qui faisait importer un nom supplémentaire dans la …
  src/Controller/AdminController.php
  src/Model/AdminRoomManager.php
Labels: Reviewed by PO

#63 Sprint04 fix03
  public/assets/css/style.css
  public/assets/images/orleans.jpg
  src/View/Room/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/WeekEnd/index.html.twig
Labels: Reviewed by PO

#64 suppression d'un bouton supprimer, ajout des messages de succès
  src/Controller/AdminController.php
  src/View/Admin/rooms.html.twig
Labels: Reviewed by PO

#65 ajout d'un message succès suite à postage de commentaire
  src/Controller/ReviewController.php
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#66 modif style page commentaire
  public/assets/css/style.css
  src/View/Review/index.html.twig
Labels: Reviewed by PO
