Repository WildCodeSchool/orleans-0219-php-grand-hotel, pull requests merged in 2019-05, with the labels that each got.

#67 Dev
  public/assets/css/style.css
  public/assets/images/orleans.jpg
  src/Controller/AdminController.php
  src/Controller/ReviewController.php
  src/Model/AdminRoomManager.php
  src/View/Admin/rooms.html.twig
  src/View/Review/index.html.twig
  src/View/Room/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/WeekEnd/index.html.twig
Labels: Reviewed by PO

#69 changement dû au rendez-vous client
  public/assets/css/style.css
  public/assets/images/orleans(1).jpg
  public/assets/images/orleans(2).jpg
  public/assets/images/orleans.jpg
  public/assets/images/orlnight.jpg
  public/assets/images/train-logo.png
  public/assets/images/tram-logo.png
  public/assets/images/voiture-logo.png
  src/View/Contact/index.html.twig
Labels: Reviewed by PO

#74 modification du <h2> en <h1>
  src/View/Galery/index.html.twig
Labels: Reviewed by PO

#75 ajustement jumbotronWE
  public/assets/images/orleans.jpg
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#71 Sprint04 us35contact
  config/db.php.dist
  src/Controller/ContactController.php
  src/Services/SendEmail.php
  src/View/Contact/index.html.twig
  src/View/Email.html.twig
Labels: Corrections done, Reviewed by PO

#77 Sprint02 us08 access
  public/assets/css/style.css
  src/View/Home/contactAccueil.html.twig
Labels: Reviewed by PO

#81 changement de content fluid en container fluid
  src/View/Seminar/index.html.twig
Labels: Reviewed by PO

#78 Sprint04 fix03
  public/assets/css/style.css
  public/assets/images/WE/jeanne.jpg
  src/View/Review/addreview.html.twig
  src/View/Review/index.html.twig
Labels: Corrections done

#79 rendre la navbar responsive
  public/assets/css/style.css
  src/View/_navbar.html.twig
Labels: Corrections done, Reviewed by PO

#82 fix ajout de l'administration services
  src/Controller/AdminController.php
  src/Model/AdminServicesManager.php
  src/View/Admin/addservice.html.twig
  src/View/Admin/services.html.twig
  src/View/layoutAdmin.html.twig
Labels: Changes requested

#84 Sprint04 fix04
  public/assets/css/style.css
  src/View/Home/contactAccueil.html.twig
  src/View/Review/index.html.twig
Labels: Reviewed by PO

#83 Dev
  config/db.php.dist
  public/assets/css/style.css
  public/assets/images/WE/jeanne.jpg
  public/assets/images/orleans(1).jpg
  public/assets/images/orleans(2).jpg
  public/assets/images/orleans.jpg
  public/assets/images/orlnight.jpg
  public/assets/images/train-logo.png
  public/assets/images/tram-logo.png
  public/assets/images/voiture-logo.png
  src/Controller/AdminController.php
  src/Controller/ContactController.php
  src/Model/AdminServicesManager.php
  src/Services/SendEmail.php
  src/View/Admin/addservice.html.twig
  src/View/Admin/services.html.twig
  src/View/Contact/index.html.twig
  src/View/Email.html.twig
  src/View/Galery/index.html.twig
  src/View/Home/contactAccueil.html.twig
  src/View/Review/addreview.html.twig
  src/View/Review/index.html.twig
  src/View/Seminar/index.html.twig
  src/View/_navbar.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed by PO

#85 inversion de l'ordre d'apparition des commentaires
  src/Model/ReviewManager.php
Labels: Reviewed by PO

#86 Sprint04 fix css
  public/assets/css/style.css
Labels: Reviewed by PO

#88 Sprint04 fix04
  public/assets/css/style.css
Labels: Reviewed by PO

#89 Dev
  public/assets/css/style.css
  src/Model/ReviewManager.php
Labels: Reviewed by PO
